# Claude Code Review
#
# This workflow runs automated code review using Claude Code when explicitly
# requested via commit message tags.
#
# HOW TO REQUEST A REVIEW:
# Include one of these tags anywhere in your commit message:
#   - [review]        - Request general code review
#   - [claude-review] - Explicitly request Claude review
#   - [code-review]   - Request code review
#
# EXAMPLES:
#   git commit -m "feat: add new feature [review]"
#   git commit -m "[claude-review] fix: resolve bug in parser"
#   git commit -m "refactor: improve performance [code-review]
#
#   This refactor optimizes the cache layer for better performance."
#
# The review will run automatically when you push commits with these tags.

name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
    # Optional: Only run on specific file changes
    # paths:
    #   - "src/**/*.ts"
    #   - "src/**/*.tsx"
    #   - "src/**/*.js"
    #   - "src/**/*.jsx"

jobs:
  claude-review:
    # Only run if commit message explicitly requests review
    if: |
      contains(github.event.head_commit.message, '[review]') ||
      contains(github.event.head_commit.message, '[claude-review]') ||
      contains(github.event.head_commit.message, '[code-review]')

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}

            Please review this pull request and provide feedback on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security concerns
            - Test coverage
            
            Use the repository's CLAUDE.md for guidance on style and conventions. Be constructive and helpful in your feedback.

            Use `gh pr comment` with your Bash tool to leave your review as a comment on the PR.
          
          # See https://github.com/anthropics/claude-code-action/blob/main/docs/usage.md
          # or https://docs.claude.com/en/docs/claude-code/sdk#command-line for available options
          claude_args: '--allowed-tools "Bash(gh issue view:*),Bash(gh search:*),Bash(gh issue list:*),Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh pr list:*)"'

