name: Publish to PyPI and GitHub Packages

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Build package
      run: uv build

    - name: Publish to PyPI
      if: github.event_name == 'release'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        uv tool install twine
        uv tool run twine upload dist/*

    - name: Publish to GitHub Packages
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      run: |
        uv tool install twine
        # Configure .pypirc for GitHub Packages
        cat > ~/.pypirc << EOF
        [distutils]
        index-servers =
            github

        [github]
        repository = https://upload.pypi.org/legacy/
        username = __token__
        password = ${{ secrets.GITHUB_TOKEN }}
        EOF

        # Upload to GitHub Packages
        uv tool run twine upload --repository github dist/*