name: Type Check

permissions:
  contents: read # For actions/checkout to fetch code
  actions: write # For actions/cache to save/restore cache

concurrency:
  group: typecheck-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
    paths:
      - "src/**/*.py"
      - "tests/**/*.py"
      - "examples/json/**/*.json"
      - "pyproject.toml"
      - "Makefile"
      - ".github/workflows/typecheck.yml"
  pull_request:
    types: [opened, synchronize]
    branches: [ main ]
    paths:
      - "src/**/*.py"
      - "tests/**/*.py"
      - "examples/json/**/*.json"
      - "pyproject.toml"
      - "Makefile"
      - ".github/workflows/typecheck.yml"

jobs:
  typecheck:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"
        enable-cache: true
    
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: uv sync --dev
    
    - name: Run ty type checker
      run: uv run ty check .
    
    - name: Run mypy type checker
      run: |
        uv run mypy -p importobot
        uv run mypy tests
        (cd scripts && uv run mypy -p importobot_scripts)
        (cd scripts && uv run mypy tests)
    
    - name: Minimize uv cache
      run: uv cache prune --ci