name: Wiki Sync

on:
  push:
    branches:
      - main
    paths:
      - 'wiki/**'
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Sync Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: wiki
          repository: ${{ github.repository }}