name: Wiki Sync

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    # Run on manual dispatch or merged PR to main
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Sync Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v5
        with:
          token: ${{ secrets.WIKI_TOKEN }}
          path: wiki
          repository: ${{ github.repository }}
